### ISSUE TITLE
Some bypasses

### ISSUE THREAD

**Issue by Bircko** [CCBlueX/LiquidBounce1.8-Issues#1521]
AAC/NCP:
instant kill
no clip
kill all enemies with one hit
crash minecraft of other players
crash pc of other players

AAC/Spartan:
add all players on server to botnet
rat all players
rat server
forceop on gamemode 1

**Comment by CrackFileso** [comment]
i think you are joking

**Comment by LAUCHTINTE337** [comment]
@Bircko do you know something about coding i think no because you are talking about like someone that never used a hack client and didnt know something about minecraft did you really think nobody had think about this before i hope you had joke please take some mor informations about a thema and after that write a comment and not before . Is it correct that you didnt know more about aac/ncp/spartan and the other anticheats as the name???????

**Comment by superblaubeere27** [comment]
No I think it's too easy for us
