### ISSUE TITLE
Low FPS !!!!and Optifine update

### ISSUE THREAD

**Issue by CrackFileso** [CCBlueX/LiquidBounce1.8-Issues#160]
①Low FPS(10 FPS -19 FPS)(no Hacks :84 FPS - 132 FPS)
②Optifine :H7 (Newest)(Don't have to update.)

**Comment by DieSchuessel** [comment]
How to fix: Buy better pc cause :84 FPS - 132 FPS ist really low

**Comment by Marco-MC** [comment]
xd

**Comment by Marco-MC** [comment]
①:
We try to improve the performance, but its not complete possible. Our Obfuscation make many things static and the flow obfuscation make the Client slower and slower. We try to find some solutions with the developer of the SmokeObfuscator.

②:
H6 and H7 performance = same
Only some issues was fixed in H7, but we have an problem if we decompile H7 Of 1.8.8... .-.
All blocks have no texture and we tried to fix the issue but we dont found a solution. :(
And ImFrozen dont know anymore how he fixed the issue in his H6 of version.
