### ISSUE TITLE
What İs This ?

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#2283]
Blink Pulse Option And Sprint Blindless Food CheckServerSide Option And Zoot/Regen NoAir Option And Fucker NoHit Option ?

**Comment by scorpion3013** [comment]
Blink Pulse: basicly toggles on and off blink to look like you are lagging
Sprint: 
1. Food if your outof food that you still sprint/not sprint
2.Blindless  if you are blind that you still sprint or no
3. CheckServerSide  checks your server side rotation to check if you are legit able to sprint in the direktion you are looking client side

 Zoot/Regen: Noair that you regen/zoot while you are in the air because that kicks you on kost server

Fucker: NoHit is that you dont have killaura and fucker working at the same time which would result 2 different rotations -> which flags aac ( if your killaura is hitting it stop destroying the block with fucker)


And use http://taco.team/ for questions and not this github. Which is for client-issues and not for questions.
