### ISSUE TITLE
.hide command for modules

### ISSUE THREAD

**Issue by itsTyrion** [CCBlueX/LiquidBounce1.8-Issues#2415]
An command like .hide <module> would be nice imo, since LiquidBounce has a sh*t ton of modules(nothing bad about that obv), since you don't gain anything from some modules being shown in the Arraylist, especially rendering stuff; Makes it look a bit more clean, seen in Flux.

**Comment by cui0v0** [comment]
I wish we can hide some commands like .say or so, too. Because some server detects your client by leting you send a message like ".say ....". For example, if server lets send  ".say example" but LiquidBounce thinks ".say" is a command, so client only sends "example" to server. So that server doesn't let us login.

**Comment by scorpion3013** [comment]
@cui0v0 could you give me some server that are doing that thing with the .say ?

**Comment by BlackHawk2306** [comment]
@cui0v0 Not like you could write .say .say example  .____.

**Comment by cui0v0** [comment]
However, server needs me to click a text and lets my client send a message. However I don't know what I sent and I can't know. So I can't bypass this detection until now.

**Comment by scorpion3013** [comment]
Just give me a serverip so i can test a bit

**Comment by cui0v0** [comment]
It is a Chinese cracked server, ip: play.qyzgmc.com

**Comment by je5442804** [comment]
What about Mouse verification?XD

**Comment by Tcm9** [comment]
nice idea.
