### ISSUE TITLE
BlackHotbar

### ISSUE THREAD

**Issue by FlorijonG** [CCBlueX/LiquidBounce1.8-Issues#294]
Wenn man diese Einstellung aktiviert kommt eine Blackhotbar mit Infos (FPS, Coordinanten etc).

**Comment by WistarWolf** [comment]
Ja. Bitte Marco :c Machs für Florijon und mich :c Du musst es ja nicht aktivieren :c So wie in Ambien halt :(

**Comment by superblaubeere27** [comment]
Wenn ich an LB mit entwickeln kann werde ich es einbauen

**Comment by SenkJu** [comment]
Nein, sorry. Sowas wollen wir nicht mehr im Client. Wer muss bitte so oft diese Daten sehen, dass man dafür nicht mal f3 drücken kann?

**Comment by WistarWolf** [comment]
@SenkJu Wieso wir es wollen? ganz einfach: Wir wollen nicht dass der Bildschirm beim drücken der F3 Taste mit so viel unnötig Daten voll ist. Wir wollen nur die wichtigsten Daten. FPS: Koodinaten, Server-IP usw. Und nicht so viel unnötiges zeug wie bei der F3 Funktion. @superblaubeere27 Wäre mega von dir.

**Comment by SenkJu** [comment]
Ja, aber wozu? Müsst ihr wirklich dauerhaft eure FPS/Koordinaten sehen? Und vergesst ihr auf welchem Server ihr gerade spielt, oder warum sollte die IP angezeigt werden?

**Comment by WistarWolf** [comment]
FPS: Ja. Die ganze Zeit F3 drücken ist nervig.
Koordinaten: Jap. Wenn man Survival oder so spielt (Auf Server halt.) oder SG oder so spielt und man einem Freund sagen will wo man ist. Und immer F3 zu drücken wird nach einer Zeit nervig finde ich und dass der Bildschirm dann auch noch mit so viel unnötigem Müll voll gespammt wird.
Und für andere Sachen z.B. Ping (Immer /ping einzugeben ist umständlich. Und wenn es den /ping Befehl nicht gibt ist es halt dann ja auch blöd wenn man seinen Ping nicht sieht.), Server-IP (Wenn man die Server IP nicht weiß weil es eine komische bzw lange IP ist und man nicht immer disconnecten will weil man vllt in einem Spiel ist.), dann vllt Datum/Uhrzeit (ESC drücken, aus dem Minecraft Bildschirm heraus gehen und in die Taskleiste schauen. Umständlich halt.) Dass sind dann halt nur ein paar hilfreiche Informationen. Wenn man das alles mit den Skripts machen könnte, würden wir nicht auch an dauernd nachfragen.

**Comment by WistarWolf** [comment]
Wieso haben es dann so viele andere Clients? Es ist halt einfach hilfreich. Ihr müsst es ja nicht aktivieren wenn ihr es nicht braucht.

**Comment by SenkJu** [comment]
Weil viele Clients, viele unnötige Sachen haben. Es mag ja sein, dass das passt zu einem Client wie Ambien, aber in der Regel sieht eine Hotbar einfach nur unfassbar hässlich aus. Und sorry, aber ich kann mir einfach nicht vorstellen, dass du so oft diese Stats brauchst. Wenn du die IP wissen willst, ohne den Server zu verlassen, benutz .serverinfo und damit ist das Thema jetzt gegessen. LiquidBounce wird keine BigBlackHotbar bekommen. Sorry.

**Comment by Benjarobbi** [comment]
Hi,
minecraft bietet dir eine integrierte Funktion die FPS permanent oben am
Bildschirmrand anzuzeigen. Frag mal Google.
Ich glaube da werden auch die Koordinaten angezeigt

Grüße,
Benjarobbi.

FPS: Ja. Die ganze Zeit F3 drücken ist nervig.
Koordinaten: Jap. Wenn man Survival oder so spielt (Auf Server halt.) oder
SG oder so spielt und man einem Freund sagen will wo man ist. Und immer F3
zu drücken wird nach einer Zeit nervig finde ich und dass der Bildschirm
dann auch noch mit so viel unnötigem Müll voll gespammt wird.
Und für andere Sachen z.B. Ping (Immer /ping einzugeben ist umständlich.
Und wenn es den /ping Befehl nicht gibt ist es halt dann ja auch blöd wenn
man seinen Ping nicht sieht.), Server-IP (Wenn man die Server IP nicht weiß
weil es eine komische bzw lange IP ist und man nicht immer disconnecten
will weil man vllt in einem Spiel ist.), dann vllt Datum/Uhrzeit (ESC
drücken, aus dem Minecraft Bildschirm heraus gehen und in die Taskleiste
schauen. Umständlich halt.) Dass sind dann halt nur ein paar hilfreiche
Informationen. Wenn man das alles mit den Skripts machen könnte, würden wir
nicht auch an dauernd nachfragen.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/294#issuecomment-305276558>,
or mute the thread

**Comment by WistarWolf** [comment]
@SenkJu Dann wäre es toll wenn man sowas wenigstens im Skript adden könnte.

**Comment by Benjarobbi** [comment]
Hi,
minecraft bietet dir eine integrierte Funktion die FPS permanent oben am
Bildschirmrand anzuzeigen. Frag mal Google.
Ich glaube da werden auch die Koordinaten angezeigt.
So gehts: 
Hold F3, press F10, release F3, press F10

**Comment by SenkJu** [comment]
Das könnten wir tun, wenn die Script Sprache dazu in der Lage wäre. Ist sie momentan aber leider nicht.

**Comment by Benjarobbi** [comment]
Die Koordinaten werden anzeigt, gerade ausprobiert 
;-)

**Comment by WistarWolf** [comment]
@SenkJu Wenn man dass bald im Skript machen könnte wäre es gut. Dann fragen wir auch nicht mehr nach ^^ Momentan bugt dass ja ein bisschen rum.

@Benjarobbi entweder bin ich dumm oder es funktioniert nicht. Ich habe es so verstanden:
F3 gedrückt halten, F10 kurz drücken, F3 Taste los lassen, F10 Taste kurz drücken.

**Comment by Benjarobbi** [comment]
@WistarWolf Google es mal kurz, da wird es erklärt.
Grüße, 
Benjarobbi

**Comment by WistarWolf** [comment]
Ich habe es gegooglet doch nichts dazu gefunden.

**Comment by Benjarobbi** [comment]
Options > Video settings > Other, then click on Show FPS
So, also das kannst du schonmal machen. Dann siehst du die FPS.

**Comment by WistarWolf** [comment]
http://prntscr.com/fed8rq ja. 
Das erste Problem ist, man sieht nicht die Koordinaten und 2. es wird so komisch über der watermark angezeigt.
