### ISSUE TITLE
LiquidWalk y cord setting & AntiBot has real uuid/name setting

### ISSUE THREAD

**Issue by zikdriver** [CCBlueX/LiquidBounce1.8-Issues#295]
MusicModule:

- Radio
- Own Music

BedFucker
- AntiBuild own Bed (BedWars)

LiquidWalk
- More Settings (Y Cord)

AntiBot
- has Bot a real UUID or Name.

**Comment by superblaubeere27** [comment]
Good idea
We try to add:

- Liquidwalk y-cord setting
- Has Bot a real UUID or Name
- And maybe AntiBuild own Bed (BedWars)

**Comment by Marco-MC** [comment]
@superblaubeere27 Achte bitte drauf was du addest, da derzeit trz nur ich an LiquidBounce code...

@zikdriver 
MusicModule >> FOR WHAT DO YOU HAVE A MUSIC PLAYER ON YOUR COMPUTER??? OR RADIO STREAMING.

BedFucker >> Idk

LiquidWalk >> What do you mean with this?

AntiBot >> Yeah could I add.

**Comment by Benjarobbi** [comment]
Die y-hohe beim Wasser festlegbar machen.

@superblaubeere27 <https://github.com/superblaubeere27> Achte bitte drauf
was du addest, da derzeit trz nur ich an LiquidBounce code...

@zikdriver <https://github.com/zikdriver>
MusicModule >> FOR WHAT DO YOU HAVE A MUSIC PLAYER ON YOUR COMPUTER??? OR
RADIO STREAMING.

BedFucker >> Idk

LiquidWalk >> What do you mean with this?

AntiBot >> Yeah could I add.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/295#issuecomment-305216852>,
or mute the thread

**Comment by zikdriver** [comment]
LiquidWalk: Das man die Position auf/unter dem Wasser (Y Koordinate) einstellen kann.
MusikModule: Ja aber ich habe keine Musik auf dem PC.

**Comment by zikdriver** [comment]
Iloveradio, Technobase ect. coole Musik.

**Comment by XaliBurMc** [comment]
Can you add

InventoryCleaner:
     - keep compass
     - keep only the best bow

**Comment by Marco-MC** [comment]
@XaliBurMc 

1 (keep compass): https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/298

**Comment by Marco-MC** [comment]
@zikdriver 

UUID AntiBot Check: https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/264
