### ISSUE TITLE
[FEATURE]Head aimpoint/vertical and horizontal aimspeed

### ISSUE THREAD

**Issue by Lytexx** [CCBlueX/LiquidBounce1.8-Issues#3382]
Head aimpoint for more reach :b

**Comment by yorik100** [comment]
It doesn't give you more reach wth

**Comment by Soulplexis** [comment]
> It doesn't give you more reach wth

yes it does actually, aiming at the head with client-side aimbot definitely will provide easier hitting of targets. in killaura it wasn;t the same because it would have been sending attacks at any range, that was just for anticheats that checked the range from the aimpoint. however in a client sided aimbot aiming for the head closes the distance more efficiently allowing you to hit further than aiming toward the center of the body or elsewhere

**Comment by yorik100** [comment]
> > It doesn't give you more reach wth
> 
> in this case it does, aiming at the head with client-side aimbot will provide a closer and easier hitting of targets. in killaura this wasn't the same because it would have been sending attacks at any range, that was just for anticheats that checked the range from the aimpoint. however in a client sided aimbot aiming for the head allows the distance to be further. efficiently allowing you to hit further than aiming toward the center of the body or elsewhere.

For aimbot yes but not for killaura

**Comment by Soulplexis** [comment]
> > > It doesn't give you more reach wth
> > 
> > 
> > in this case it does, aiming at the head with client-side aimbot will provide a closer and easier hitting of targets. in killaura this wasn't the same because it would have been sending attacks at any range, that was just for anticheats that checked the range from the aimpoint. however in a client sided aimbot aiming for the head allows the distance to be further. efficiently allowing you to hit further than aiming toward the center of the body or elsewhere.
> 
> For aimbot yes but not for killaura

wasnt he talking about aimbot.

**Comment by Lytexx** [comment]
No im dumb sry lol only when killaura would not modify range it would give you more reach
