### ISSUE TITLE
[FEATURE] %tps% in CustomHud

### ISSUE THREAD

**Issue by Leejames2305** [CCBlueX/LiquidBounce1.8-Issues#3416]
Able to show TPS of server in CustomHud

**Comment by superblaubeere27** [comment]
This is not possible since the TPS values are never sent to the client.

**Comment by superblaubeere27** [comment]
I will close this one since it is not possible to implement it. On some servers TPS are displayed in the scoreboard or when you use `/tps`; you could get it from that source, but it would be a dirty implementation. If I am wrong and the TPS are part of the standard minecraft protocol, I will add it.

**Comment by Leejames2305** [comment]
@superblaubeere27 But some old client like Jigsaw and Future actually have TPS counter build into it . I pretty sure that it is possible but maybe hard to implement into the client .

**Comment by superblaubeere27** [comment]
@Leejames2305 I didn't want to say that it is impossible. It's just a dirty implementation which as I think shouldn't be in LiquidBounce

**Comment by leumasme** [comment]
tps can be estimated clientside by daytime updates, which is generally how other clients do it.
