### ISSUE TITLE
[FEATURE] AutoPot Option For

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3468]
Other Potions Like Speed Fire Resistance etc

**Comment by superblaubeere27** [comment]
But AutoPot is health related. It will use health pots when you are low on health. Why should it use Fire Resistance Potions?

**Comment by Teals53** [comment]
so i dont need splash this potions on skywars with my hands after put away health potions then take it back or close module

**Comment by superblaubeere27** [comment]
This is not the intention of the module.

> Automatically throws healing potions.

I think this sentence is clear.

![grafik](https://user-images.githubusercontent.com/22642852/73308803-54a9f580-4221-11ea-9898-5554aab9fe5e.png)

This shouldn't be an option of `AutoPot` since it has nothing to do with `AutoPot`.
We could make a new module for it, but if we added this feature there would be some problems to solve like when to throw the potions, because the best timing is impossible to determine. This is why I don't think that any cheat needs this feature. If you want to have a new module which does that, create a new feature request. I will close this one since idc why it should be an option of `AutoPot`. If @kawaiinekololis is disagrees he can reopen it.
