### ISSUE TITLE
[FEATURE]Add backlist for AutoArmor

### ISSUE THREAD

**Issue by SanJiYT** [CCBlueX/LiquidBounce1.8-Issues#3621]
Add Blacklist for AutoArmor
Ex : I Want to Pick Diamond Armor instead Leather Armor with Protection IV add a Blacklist so we can type the item ID for AutoArmor don't pick that item because on some servers the Diamond Armor without any enchantments will better than Leather Armor with Protection IV 

My english is bad sorry

**Comment by yorik100** [comment]
Ye I thought so, the calcs aren't really THAT accurate

**Comment by Tcm9** [comment]
I would rather prioritize.

-Best (autoarmor prioritized by armor bar) 

-Armor (Autoarmor prioritized by armor bar) (Currently)

-Enchantment (Autoarmor prioritized by enchantments)

-projectiles (Autoarmor prioritizes after best defense against bows)

**Comment by superblaubeere27** [comment]
@Tcm9 Dude that is what we are doing in the moment ._.

**Comment by superblaubeere27** [comment]
If you want to change it, you can create a fork and implement it, but for the majority of users it is completely useless and we don't want to flood the client with useless features :/

**Comment by yorik100** [comment]
Diamond chestplate is better than leather prot 4 in 99% of the cases

**Comment by superblaubeere27** [comment]
@yorik100 Protection 4 has a DamageReduction of `16%`, while Diamond-Armor without any enchantments has `12%`. Why in the world should the diamond armor be taken?

**Comment by yorik100** [comment]
> 
> 
> @yorik100 Protection 4 has a DamageReduction of `16%`, while Diamond-Armor without any enchantments has `12%`. Why in the world should the diamond armor be taken?

"1 defense point is half of a chestplate in the armor bar. Each defense point reduces any damage dealt to the player, which is absorbed by armor by 4%"
Diamond chestplate : 8 armor points, 8 times 4 is 32
Leather chestplate 3 times 4 is 12
"The formula for damage reduction is (4 × level)% for each armor point. The highest level (full Protection IV) absorbs +16% (4 × 4%) of damage. Theoretically at level 25 no damage is possible (because it would transcend 100%), but because the damage to be absorbed is capped at 80%, the maximum effective level would be 20. "
Leather chestplate prot 4 : 12 + 4 * 4 which is 28
Nope, the diamond chestplate is better

**Comment by yorik100** [comment]
https://streamable.com/7b27r Pay attention to the down-left corner, where my cursor is showing, it shows the total protection
