### ISSUE TITLE
[BUG] Autoarmor calcs are wrong

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3623]
**Describe the bug**
It prefers prot 4 leather chestplate rather than unenchanted diamond chestplate
"1 defense point is half of a chestplate in the armor bar. Each defense point reduces any damage dealt to the player, which is absorbed by armor by 4%"
Diamond chestplate : 8 armor points, 8 times 4 is 32
Leather chestplate 3 times 4 is 12
"The formula for damage reduction is (4 × level)% for each armor point. The highest level (full Protection IV) absorbs +16% (4 × 4%) of damage. Theoretically at level 25 no damage is possible (because it would transcend 100%), but because the damage to be absorbed is capped at 80%, the maximum effective level would be 20. "
Leather chestplate prot 4 : 12 + 4 * 4 which is 28
https://streamable.com/7b27r Vanilla Enhanced mod shows me that I'm right (ofc Vanilla Enhanced calcs are more accurate), look at the down left corner showing the % of protection

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by superblaubeere27** [comment]
A diamond chestplate alone has `8` Defense Points. This, NOTHING ELSE, is the formular to calculate the damage reduction. 
![grafik](https://user-images.githubusercontent.com/22642852/76161596-2deeb100-6135-11ea-932d-a1d7f683cae7.png)
 So the Diamond Chestplate alone has `12%` Reduction while the Leather Chestplate (`3DP`) has `2,4%`. The calculation for Protection is `(4 * lvl)%` (https://minecraft.gamepedia.com/Protection), so the Leather Armor with Protection 4 has `16%` Damage reduction. If you multiply it, the leather armor will have `18,016%` Damage reduction while the Diamond Armor has `12%`. 

WHY IN THE WORLD IS IT SUPPOSE TO TAKE THE DIAMOND ARMOR?

I spent hours making this AutoArmor calculate the real damage reduction, but you still report it is a bug. WTF? Do you are have stupid? Vanilla Enhanchements calculates the POTENTIAL. `4%` comes from `80% / 20 Defense Points`. `80%` is just a threshold and has **NOTHING** to do with the reality. The mod tries to calculate a **POTENTIAL** and not the actual value. It tries to tell approximately you how good your Armor is, which is doesn't do because it's calculations are bullshit.

You should think about what a mod really calculates, before you start the decompiler. Here is btw the code you looked at: 
![grafik](https://user-images.githubusercontent.com/22642852/76162084-34cbf280-613a-11ea-9589-0f7010d7beb2.png)
And here is the article you should have read instead of using a decompiler: https://minecraft.gamepedia.com/Armor
