### ISSUE TITLE
LiquidBounce 1.12.2

### ISSUE THREAD

**Issue by JeffKrit** [CCBlueX/LiquidBounce1.8-Issues#3644]
why don't you develop Liquid Bounce 1.12.2 further ?

**Comment by NurMarvin** [comment]
It's quite hard to maintain multiple versions because we have to port everything from the 1.8 version to 1.12.2.
Maybe at some point we will add multiple protocol version support to the 1.8 version, so you can use it to connect to newer versions, similar to what Sigma did it in it's recent update but I can't give you an ETA since it's unclear if we can implement such functionality without producing too many flags in newer versions due to how the client handles stuff differently in 1.8 compared to e.g. 1.15.
