### ISSUE TITLE
Gg

### ISSUE THREAD

**Issue by Teals53** [CCBlueX/LiquidBounce1.8-Issues#3857]
Rip marco and big F for LiquidBounce

No one not need to say me its not dead we can still contribute this we have script api source bla bla just stop it everyone can see contributing percent of Lb so liquidbounce without marco is like football without ball. i hope marco can be go free and thanks for everything if marco not can be come back.

Also i wonder why marco do this attack ? Just for what?

**Comment by Teals53** [comment]
Ok closing without saying anything and let me think your reason is "its not a place for talking that" right? XD but idc this it doesnt matter for me

**Comment by Trol** [comment]
did I ask

**Comment by NurMarvin** [comment]
This issue was closed because it doesn't belong here.
If you wish to have a conversation about LiquidBounce you can do that in the forums in the [General Discussion](https://forums.ccbluex.net/category/2/general-discussion) category, or if you want to have an off-topic conversation you can do so in the [Off-Topic](https://forums.ccbluex.net/category/12/off-topic) category of the forums, former of which already has a thread on this specific topic by other members.
