### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by Litely1222** [CCBlueX/LiquidBounce1.8-Issues#3890]
i need color picker for liquidbounce i cant find it

**Comment by Leejames2305** [comment]
Wait what ? You need it for what ? I thought the RGB value slider is enough already

**Comment by Litely1222** [comment]
> Wait what ? You need it for what ? I thought the RGB value slider is enough already

        Fonts.fontBold180.drawCenteredString("AntiForge", (int) (width / 2F), (int) (height / 8F + 5F), 4673984, true);
color is 4673984 i want change it

**Comment by NurMarvin** [comment]
Getting these colors is pretty easily since it's very similar to the 8-digit hex color format.
In practice you would need to follow this syntax:
```
0xAARRGGBB
```
with `AA` being the alpha value, `RR` being the red value, `GG` being the green value and `BB` being the blue value.
All of the values above are in a hexadecimal format and range from 0 to 255.
If you e.g. want a fully opaque bright red, which in hex color format would be #FF0000, you would put `0xFFFF0000`.

**Comment by NurMarvin** [comment]
I also went ahead and updated the color in question in the LiquidBounce source since the color format wasn't supposed to be like that.

**Comment by Litely1222** [comment]
hmm ty
